Repository Insideouuut/Insideouuut_frontend, pull requests merged in 2024-08, with the labels that each got.

#61 [#55] 💄 채팅방 목록 조회
  src/assets/lottie/chat.json
  src/components/Header.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/ChatRoomList.tsx
  src/pages/chat/chatMockData.ts
  src/routes/routes.tsx
Labels: 희선, 💄 Design

#64 #10 feature/auth 로그인 및 회원가입 API 수정
  src/api/authApi.ts
  src/api/axiosConfig.ts
  src/assets/lottie/userinfo.json
  src/pages/Auth/Login.tsx
  src/pages/Auth/Signup.tsx
  src/pages/Auth/UserInfo.tsx
  src/pages/Auth/UserInfoForm.tsx
  src/routes/routes.tsx
  src/types/Auth.ts
Labels: 경민, ✨ Feature, 🐞 BugFix, 📬 API

#65 #26 feature/create modong 모동 생성 폼 수정
  package-lock.json
  package.json
  patches/@radix-ui+react-radio-group+1.2.0.patch
  src/api/createModongApi.ts
  src/pages/CreateModong/CreateClub.tsx
  src/pages/CreateModong/CreateClubForm.tsx
  src/pages/CreateModong/CreateMeeting.tsx
  src/pages/CreateModong/CreateMeetingForm.tsx
  src/routes/routes.tsx
  src/types/Modong.ts
Labels: 경민, ✨ Feature, 🔨 Refactor

#66 [#10] 🚑 토큰 헤더 값 수정
  src/pages/Auth/Login.tsx
Labels: 경민, 🐞 BugFix

#67 [#10] ✨ 카카오 로그인 구현
  index.html
  public/modong.svg
  public/vite.svg
  src/api/api.ts
  src/api/authApi.ts
  src/pages/Auth/IsFirstKakaoLogin.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/Reissue.tsx
  src/pages/Auth/UserInfoForm.tsx
  src/pages/MyPage/mockUserData.ts
  src/routes/routes.tsx
  src/store/userStore.ts
Labels: 경민, ✨ Feature, 🐞 BugFix, 📬 API

#69 [#68] ✨ Swagger - TS 연동
  package-lock.json
  package.json
  src/api/Apis.ts
  src/api/data-contracts.ts
  src/api/http-client.ts
Labels: 희선, ⚙ Setting, ✨ Feature

#71 #20 feature/마이페이지 api 연동
  src/pages/Auth/Login.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/UpdateUser.tsx
  src/types/Meeting.ts
  src/types/User.ts
Labels: 희선, ✨ Feature, 📬 API, 💄 Design

#73 [#20] ✨프로필 이미지 불러오기 및 매너온도 설정
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/UpdateUser.tsx
Labels: 희선, 📬 API, 💄 Design

#74 [#53] 🔨헤더 로그인 여부 수정
  src/components/Header.tsx
  src/pages/MyPage/MyPage.tsx
Labels: 희선, 🐞 BugFix, 💄 Design, 🎨 Style

#76 #75 feature/프로필 location조회
  fetch-swagger.js
  package-lock.json
  package.json
  src/api/Apis.ts
  src/api/chatApi.ts
  src/api/userApi.ts
  src/components/Header.tsx
  src/components/ui/popover.tsx
  src/components/ui/profileModal.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/UpdateUser.tsx
  src/pages/SetLocation/SetLocation.tsx
  src/pages/chat/ChatRoom.tsx
Labels: 희선, ✨ Feature, 📬 API, 💄 Design, 👷 CI/CD

#77 #46 feature/동아리관리자페이지
  src/api/Apis.ts
  src/api/searchApi.ts
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/SearchPage/SearchResults.tsx
  src/pages/SearchPage/searchHero.tsx
Labels: 📬 API

#78 #55 feature/채팅 세부구현
  src/api/chatApi.ts
  src/components/Header.tsx
  src/pages/chat/ChatRoom.tsx
Labels: 희선, ✨ Feature, 📬 API, 💄 Design

#79 #46 feature/동아리관리자페이지
  src/api/Apis.ts
  src/api/clubApi.ts
  src/api/meetingApi.ts
  src/api/searchApi.ts
  src/pages/ClubPage/ClubHero.tsx
  src/pages/ClubPage/ClubManagement.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/ClubPage/MemberApproval.tsx
  src/pages/ClubPage/MemberManagement.tsx
  src/pages/ClubPage/MyMeeting.tsx
  src/pages/SearchPage/SearchResults.tsx
  src/types/MeetingApplicantsTypes.ts
  src/types/Member.ts
  src/types/MemberAuthorityResponse.ts
Labels: 📬 API

#84 [#19] ✨ feature/메인페이지
  src/api/Apis.ts
  src/components/GroupCard.tsx
  src/pages/Main/MiddleSection.tsx
  src/pages/Main/NewCard.tsx
  src/utils/cardUtils.ts
  src/utils/timeUtils.ts
Labels: 희선, ✨ Feature, 📬 API, 🔨 Refactor, 💄 Design, 🎨 Style

#88 #26 feature/create-modong 카카오 장소 검색 기능 추가
  src/api/axiosConfig.ts
  src/api/createModongApi.ts
  src/pages/CreateModong/CreateClubForm.tsx
  src/pages/CreateModong/CreateMeetingForm.tsx
  src/pages/CreateModong/Map.tsx
  src/types/Modong.ts
Labels: 경민, ✨ Feature, 🔨 Refactor

#91 [#44] ✨ 게시글 CRUD 연동 및 내 참여/대기/종료 모임 조회
  package-lock.json
  package.json
  src/api/Apis.ts
  src/api/api.ts
  src/pages/ClubPage/ClubHero.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/Main/NewCard.tsx
  src/pages/MyPage/MyModong.tsx
  src/pages/MyPage/UpdateUser.tsx
  src/pages/MyPage/useFetchProfile.ts
  src/pages/board/BoardList.tsx
  src/pages/board/PostDetail.tsx
  src/pages/board/PostForm.tsx
  src/pages/board/mockPosts.ts
  src/pages/chat/Bubble.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/socket.ts
  src/routes/routes.tsx
  src/utils/cardUtils.ts
  src/utils/timeUtils.ts
  vite.config.ts
Labels: 희선, ✨ Feature, 📬 API, 🔨 Refactor, 💄 Design, 🎨 Style

#92 [#89] 🐛 로그인 시 유저 정보 상태 관리에 저장
  src/pages/Auth/Login.tsx
Labels: 경민, 🐞 BugFix

#93 [#19] 💄 메인페이지 디자인 수정 및 로그인 여부 버그 수정
  src/pages/CreateModong/CreateClub.tsx
  src/pages/CreateModong/CreateMeeting.tsx
  src/pages/Main/CategoryContainer.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/NewCard.tsx
  src/utils/cardUtils.ts
Labels: 희선, 🐞 BugFix, 💄 Design

#94 [#39] 멤버리스트 API 연동
  src/api/clubApi.ts
  src/pages/ClubPage/ClubMember.tsx
  src/pages/ClubPage/ClubMemberList.tsx
  src/pages/ClubPage/MeetingMember.tsx
  src/pages/ClubPage/MeetingMemberList.tsx
  src/pages/ClubPage/MemberList.tsx
  src/routes/routes.tsx
Labels: 경민, 📬 API

#96 #19 feature/메인페이지
  src/components/GroupCard.tsx
  src/pages/Main/MiddleSection.tsx
  src/pages/Main/NewCard.tsx
  src/utils/cardUtils.ts
Labels: 희선, 💄 Design

#97 #46 feature/동아리관리자페이지
  src/api/clubApi.ts
  src/api/meetingApi.ts
  src/api/searchApi.ts
  src/components/GroupCard.tsx
  src/pages/ClubPage/ClubHero.tsx
  src/pages/ClubPage/ClubMain.tsx
  src/pages/ClubPage/ClubManagement.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/ClubPage/MemberApproval.tsx
  src/pages/ClubPage/MyMeeting.tsx
  src/pages/GroupJoinPage/ClubRegistration.tsx
  src/pages/GroupJoinPage/groupjoinApi.tsx
  src/pages/Main/MiddleSection.tsx
  src/pages/Main/NewCard.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/pages/SearchPage/SearchResults.tsx
  src/pages/SearchPage/searchHero.tsx
  src/routes/routes.tsx
  src/types/Clubs.ts
  src/types/Meetings.ts
  src/types/Search.ts
Labels: 📬 API

#98 [#19] 💄 그룹 카드 수정
  src/components/GroupCard.tsx
  src/pages/Main/MiddleSection.tsx
  src/pages/Main/NewCard.tsx
  src/pages/SearchPage/SearchPage.tsx
  src/types/Search.ts
Labels: 희선, 🐞 BugFix, 💄 Design

#100 [#26] 모임 및 동아리 생성 버그 수정
  src/pages/CreateModong/CreateClubForm.tsx
  src/pages/CreateModong/CreateMeetingForm.tsx
Labels: 경민, ✨ Feature, 🐞 BugFix

#106 [#105] 회원가입 시 내 지역 입력 삭제
  src/pages/Auth/Signup.tsx
  src/types/Auth.ts
Labels: 경민, 🐞 BugFix

#107 #20 feature/마이페이지
  index.html
  src/pages/Auth/Signup.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/UpdateUser.tsx
  src/pages/MyPage/mockUserData.ts
  src/pages/SetLocation/SetLocation.tsx
  src/store/userStore.ts
Labels: 희선, 🎨 Style

#108 [#44] ✨ 게시판
  src/api/Apis.ts
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/board/PostDetail.tsx
  src/store/userStore.ts
Labels: 희선, ✨ Feature, 🐞 BugFix, 📬 API

#111 [#109] 소켓 연결 및 채팅 기능, 스크롤 구현
  src/api/Apis.ts
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/chat/Bubble.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatRoom.tsx
  src/routes/routes.tsx
  src/types/Meetings.ts
Labels: 희선, ✨ Feature, 🐞 BugFix, 📬 API

#112 #110 fix/세부수정
  src/components/ui/avatar.tsx
  src/pages/ClubPage/ClubHero.tsx
  src/pages/ClubPage/ClubMain.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/ClubPage/MemberApproval.tsx
Labels: 희선, 🐞 BugFix

#115 [#114] ♻️ 푸터 내용 및 링크 수정
  src/components/Footer.tsx
Labels: 경민, 🔨 Refactor

#118 [#113] 신고하기 및 특정 유저 프로필 조회 구조 생성
  src/api/userApi.ts
  src/pages/ClubPage/member/ClubMember.tsx
  src/pages/ClubPage/member/ClubMemberList.tsx
  src/pages/ClubPage/member/MeetingMember.tsx
  src/pages/ClubPage/member/MeetingMemberList.tsx
  src/pages/ClubPage/member/ReportUser.tsx
  src/pages/ClubPage/member/UserProfile.tsx
  src/routes/routes.tsx
Labels: 경민, ✨ Feature, 🔨 Refactor

#119 [#113] ✨ 버튼 클릭 시 실행되는 함수 추가
  src/pages/ClubPage/member/ClubMember.tsx
  src/pages/ClubPage/member/MeetingMember.tsx
Labels: 경민

#120 [#113] ✨ 특정 유저 조회, 좋아요, 신고기능 추가
  package-lock.json
  package.json
  src/components/ui/progress.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/member/ClubMember.tsx
  src/pages/ClubPage/member/ClubMemberList.tsx
  src/pages/ClubPage/member/MeetingMember.tsx
  src/pages/ClubPage/member/MeetingMemberList.tsx
  src/pages/ClubPage/member/UserProfile.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/chat/chatMockData.ts
  src/pages/chat/socket.ts
  src/routes/routes.tsx
Labels: 희선, ✨ Feature, 📬 API

#122 🐛 동네 설정 반경 fix
  public/location.geojson
  src/global.d.ts
  src/pages/SetLocation/MapComponent.tsx
Labels: 희선, 🐞 BugFix, 📬 API, 🎨 Style

#124 [#123] 🐛 UI 관련 잔고장
  src/pages/ClubPage/ClubMain.tsx
  src/pages/Main/MiddleSection.tsx
  src/pages/Main/middle.png
  src/pages/chat/ChatRoom.tsx
Labels: 희선, 🐞 BugFix, 💄 Design
