Repository Insideouuut/Insideouuut_frontend, pull requests merged in 2024-07, with the labels that each got.

#2 [#1] 🎉 프로젝트 초기 설정
  .env
  .eslintrc.cjs
  .github/issue_template.md
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  README.md
  index.html
  jest.config.js
  jest.setup.ts
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 희선, ⚙ Setting

#5 #4 feature/cicd pipeline
  .github/workflows/ci.yml
  .prettierrc
  src/App.tsx
  src/assets/react.svg
Labels: 경민, 🎨 Style, 👷 CI/CD

#6 💚 CI 파이프라인 구축 중 테스트 관련 오류 수정
  .github/workflows/ci.yml
  package.json
Labels: 경민, 🐞 BugFix, 👷 CI/CD

#7 [#4] CD 파이프라인 구축
  .github/workflows/cicd.yml
  src/App.tsx
Labels: 경민, 👷 CI/CD

#12 💄 폰트 및 테마 적용
  app/globals.css
  src/App.css
  src/App.tsx
  src/index.css
  src/index.tsx
  tailwind.config.js
Labels: 경민, ⚙ Setting

#16 #13 feature/랜딩페이지
  src/App.tsx
  src/components/icons/game.png
  src/components/icons/location.svg
  src/components/icons/logo.png
  src/components/icons/modongtmp.svg
  src/components/icons/note.svg
  src/components/icons/notification_active.svg
  src/components/icons/notification_default.svg
  src/components/icons/profile.webp
  src/components/icons/review.svg
  src/components/icons/run.png
  src/components/icons/study.png
  src/components/icons/talk.png
  src/components/ui/Footer.tsx
  src/components/ui/Header.tsx
  src/components/ui/notificationModal.tsx
  src/components/ui/profileModal.tsx
  src/pages/LandingPage/Infomation.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LandingPage/SecondSection.tsx
  src/pages/LandingPage/SocialSection.tsx
  src/pages/LandingPage/ThirdSection.tsx
  src/routes/routes.tsx
  tailwind.config.js
Labels: 주환, ✨ Feature, 💄 Design

#17 #11 feature/동네설정
  .env
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/lottie/setlocation.json
  src/components/HeroSection.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/input.tsx
  src/components/ui/menubar.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/popover.tsx
  src/global.d.ts
  src/pages/Example.tsx
  src/pages/SetLocation/MapComponent.tsx
  src/pages/SetLocation/SetLocation.tsx
  src/routes/routes.tsx
  tailwind.config.js
Labels: 희선, ✨ Feature, 🎨 Style

#18 🎨 디렉토리 수정
  src/assets/icons/game.png
  src/assets/icons/location.svg
  src/assets/icons/logo.png
  src/assets/icons/modongtmp.svg
  src/assets/icons/note.svg
  src/assets/icons/notification_active.svg
  src/assets/icons/notification_default.svg
  src/assets/icons/profile.webp
  src/assets/icons/review.svg
  src/assets/icons/run.png
  src/assets/icons/study.png
  src/assets/icons/talk.png
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/LandingPage/Infomation.tsx
  src/pages/LandingPage/LandingPage.tsx
  src/pages/LandingPage/SecondSection.tsx
  src/pages/LandingPage/SocialSection.tsx
  src/pages/LandingPage/ThirdSection.tsx
  src/pages/SetLocation/SetLocation.tsx
Labels: 희선, 🎨 Style

#25 #10 feature/auth 로그인 및 회원가입
  package-lock.json
  package.json
  src/assets/lottie/hi.json
  src/components/Header.tsx
  src/components/ui/form.tsx
  src/components/ui/label.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/pages/Auth/Login.tsx
  src/pages/Auth/Signup.tsx
  src/routes/routes.tsx
Labels: 경민, ✨ Feature, 💄 Design

#33 #13 feature/랜딩페이지
  src/assets/lottie/communication.json
  src/assets/lottie/people.json
  src/assets/lottie/search.json
  src/assets/lottie/social.json
  src/pages/LandingPage/Infomation.tsx
  src/pages/LandingPage/SecondSection.tsx
  src/pages/LandingPage/SocialSection.tsx
  src/pages/LandingPage/ThirdSection.tsx
Labels: ✨ Feature, 💄 Design

#35 #26 feature/모동 생성
  package-lock.json
  package.json
  src/assets/lottie/together.json
  src/components/ui/calendar.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/slider.tsx
  src/components/ui/textarea.tsx
  src/pages/Create/CreateClub.tsx
  src/pages/Create/CreateClubForm.tsx
  src/pages/Create/CreateMeeting.tsx
  src/pages/Create/CreateMeetingForm.tsx
  src/routes/routes.tsx
Labels: 경민, ✨ Feature, 💄 Design

#36 #19 feature/메인페이지
  app/globals.css
  package-lock.json
  package.json
  src/assets/lottie/main.json
  src/assets/lottie/together.json
  src/components/GroupCard.tsx
  src/components/HeroSection.tsx
  src/components/dummyData.ts
  src/components/ui/badge.tsx
  src/pages/Main/BottomBG.png
  src/pages/Main/CategoryButton.tsx
  src/pages/Main/CategoryContainer.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/MiddleSection.tsx
  src/pages/Main/ModongCard.tsx
  src/pages/SearchPage/SearchResults.tsx
  src/routes/routes.tsx
  tailwind.config.js
Labels: 희선, ✨ Feature, 💄 Design, 🎨 Style

#38 #20 feature/마이페이지
  package-lock.json
  package.json
  src/components/ui/menubar.tsx
  src/components/ui/tabs.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/UpdateUser.tsx
  src/pages/MyPage/mockUserData.ts
  src/routes/routes.tsx
  src/store/userStore.ts
  tailwind.config.js
Labels: 희선, ✨ Feature, 💄 Design

#41 #39 feature/멤버 리스트
  package-lock.json
  package.json
  src/components/ui/avatar.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/ClubPage/Member.tsx
  src/pages/ClubPage/MemberList.tsx
  src/pages/ClubPage/ex.tsx
Labels: 경민, ✨ Feature, 💄 Design

#42 #10 feature/auth 회원가입 유효성 오류 수정
  src/pages/Auth/Login.tsx
  src/pages/Auth/Signup.tsx
Labels: 경민, 🐞 BugFix, 💄 Design

#48 #44 feature/게시판
  src/components/ui/pagination.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/board/BoardList.tsx
  src/pages/board/PostDetail.tsx
  src/pages/board/mockPosts.ts
  src/routes/routes.tsx
  src/utils/boardMapping.ts
Labels: 희선, ✨ Feature, 🔨 Refactor, 💄 Design, 🎨 Style

#57 #46 feature/동아리관리자페이지
  package-lock.json
  package.json
  src/components/GroupCard.tsx
  src/pages/ClubPage/ApplyModal.tsx
  src/pages/ClubPage/ClubHero.tsx
  src/pages/ClubPage/ClubMain.tsx
  src/pages/ClubPage/ClubManagement.tsx
  src/pages/ClubPage/ClubPage.tsx
  src/pages/ClubPage/ClubSidebar.tsx
  src/pages/ClubPage/MeetingList.tsx
  src/pages/ClubPage/MemberApproval.tsx
  src/pages/ClubPage/MemberManagement.tsx
  src/pages/ClubPage/ex.tsx
  src/pages/SearchPage/SearchResults.tsx
  src/pages/SearchPage/searchHero.tsx
  src/routes/routes.tsx
Labels: ✨ Feature, 💄 Design

#58 #47 feature/axios setting
  src/api/api.ts
  src/api/authApi.ts
  src/api/axiosConfig.ts
  src/types/Auth.ts
Labels: 경민, 📬 API

#59 [#47] ♻️ GET, POST 요청 함수 모듈화
  src/api/api.ts
Labels: 경민, 📬 API, 🔨 Refactor

#60 #10 feature/auth 로그인 및 회원가입 API 연동
  package-lock.json
  src/api/authApi.ts
  src/pages/Auth/Login.tsx
  src/pages/Auth/Signup.tsx
  src/types/Auth.ts
Labels: 경민, 📬 API, 🔨 Refactor
